// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

var renderer = {
  prepare: (function (param) {
      
    }),
  render: (function (param) {
      return JsxRuntime.jsx("div", {
                  children: "404"
                });
    })
};

export {
  renderer ,
}
/* react/jsx-runtime Not a pure module */
