// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Page1 from "../Page1.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var renderer = {
  prepare: (function (param) {
      
    }),
  render: (function (param) {
      return JsxRuntime.jsx(Page1.make, {});
    })
};

export {
  renderer ,
}
/* Page1 Not a pure module */
