// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RootPage from "../RootPage.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var renderer = {
  prepare: (function (param) {
      
    }),
  render: (function (param) {
      return JsxRuntime.jsx(RootPage.make, {});
    })
};

export {
  renderer ,
}
/* RootPage Not a pure module */
