// Generated by ReScript, PLEASE EDIT WITH CARE


var Root = {
  Route: undefined
};

var Page1 = {
  Route: undefined
};

var FourOhFour = {
  Route: undefined
};

export {
  Root ,
  Page1 ,
  FourOhFour ,
}
/* No side effect */
