// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as React from "react";
import * as Router from "./Router.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as RelayRouter from "rescript-relay-router/src/RelayRouter.mjs";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactErrorBoundary from "@rescript/react/src/RescriptReactErrorBoundary.mjs";

import './index.css'
;

var domElement = document.querySelector("#root");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(JsxRuntime.jsx(React.StrictMode, {
            children: JsxRuntime.jsx(RelayRouter.Provider.make, {
                  value: Router.routerContext,
                  children: JsxRuntime.jsx(React.Suspense, {
                        children: Caml_option.some(JsxRuntime.jsx(RescriptReactErrorBoundary.make, {
                                  children: JsxRuntime.jsx(App.make, {}),
                                  fallback: (function (param) {
                                      return "Error!";
                                    })
                                })),
                        fallback: "Loading..."
                      })
                })
          }));
}

export {
  
}
/*  Not a pure module */
