// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Route__Root_route from "./routes/__generated__/Route__Root_route.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RelayRouter__Utils from "rescript-relay-router/src/RelayRouter__Utils.mjs";

function Page1(props) {
  var match = RelayRouter__Utils.useRouter();
  var push = match.push;
  React.useEffect((function () {
          push(Route__Root_route.makeLink());
        }), []);
  return JsxRuntime.jsx("div", {
              children: "This is page1"
            });
}

var make = Page1;

export {
  make ,
}
/* react Not a pure module */
