// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RelayRouter__Link from "rescript-relay-router/src/RelayRouter__Link.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as Route__Page1_route from "./routes/__generated__/Route__Page1_route.mjs";

function RootPage(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                "Welcome home!",
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(RelayRouter__Link.make, {
                      to_: Route__Page1_route.makeLink(),
                      children: "if you click here, you'll go to page1 and come back here automatically"
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                "but if you copy paste http://localhost:5173/page1 in the URL bar of your browser, you'll go to page1 and the URL will be set back to home page but the content of page1 wil remain."
              ]
            });
}

var make = RootPage;

export {
  make ,
}
/* RelayRouter__Link Not a pure module */
